---

- name: config| install npm for CLI [{{ user.username }}]
  become: true
  become_user: root
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - npm

- name: config| install the CLI [{{ user.username }}]
  npm:
    name: joplin
    path: ~/.joplin-bin

- name: config| use CLI to generate database and update settings [{{ user.username }}]
  command: ~/.joplin-bin/bin/joplin config '{{ item.key }}' '{{ item.val }}'
  with_items:
    - "{{ user.settings }}"
  no_log: true

- name: config| create GUI config directory [{{ user.username }}]
  file:
    path: ~/.config/joplin-desktop
    state: directory

- name: config| copy the CLI database to the GUI location [{{ user.username }}]
  copy:
    src: ~/.config/joplin/database.sqlite
    dest: ~/.config/joplin-desktop
    remote_src: true
